#!/bin/sh
#
# Install script for Raspbian that can be run after compiling binaries.
#
# a) sudo apt-get install sqlite3; sudo apt-get install libsqlite3-dev; 
#
# b) cd src; make
# 
# c) sudo ./install (this script)
#
# d) sudo raspi-config (to enable I2C and SPI) 
#
# e) journalctl -u i2chipd.service --follow -p info
#
# f) sudo systemctl start i2chipd.service 
# 
#
# The directories used and files created by this script:
#
# /etc/i2chipd_conf                  - configuration file
# /usr/sbin/i2chipd                  - chip reading service 
# /var/lib/i2chipd/                  - live physical data
#
# Thu Jul 30 20:48:17 CDT 2020
# Edit: 
# 
# Jaakko Koivuniemi
#


# source directory for 'I2chipd'
SOURCEDIR=${PWD}
SOURCEBIN=${SOURCEDIR}/src

# binary executables 
BINDIR=/usr/sbin

# systemd unit configuration file
UNITCONF=/lib/systemd/system

# for configuration file
CONFDIR=/etc

# live data 
VARLIBDIR=/var/lib

# binary executables
BINS='i2chipd'

if [ -d $SOURCEBIN ]; then
  echo "Copy binary executables to ${BINDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEBIN}/${item} ]; then
       echo "... ${item}"
       /usr/bin/install -C -m 755 ${SOURCEBIN}/${item} ${BINDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEBIN} does not exist"
fi

if [ ! -r ${UNITCONF}/i2chipd.service ]; then
  echo "Write systemd unit configuration file ${UNITCONF}/i2chipd.service"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/i2chipd.service ${UNITCONF} 
else
  echo "Configuration file ${UNITCONF}/i2chipd.service already exists" 
fi

if [ ! -r ${CONFDIR}/i2chipd_conf ]; then
  echo "Write default configuration file ${CONFDIR}/i2chipd_conf"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/i2chipd_conf ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/i2chipd_conf already exists" 
fi

if [ -d /var/lib/i2chipd ]; then
  echo "Directory /var/lib/i2chipd already exists"
else
  echo "Create directory /var/lib/i2chipd"
  /bin/mkdir -m 775 /var/lib/i2chipd
fi

if [ ! -r /var/lib/i2chipd/i2chipd.db ]; then
  echo "Create database with empty tables /var/lib/i2chipd/i2chipd.db"
  /usr/bin/sqlite3 /var/lib/i2chipd/i2chipd.db < table/sqlite-init
else
  echo "Database /var/lib/i2chipd/i2chipd.db already exists"
fi

